import { useState } from 'react';
import { toast } from 'sonner';
import api from '../lib/api';
import { logger } from '../lib/logger';
import LoadingSpinner from '../components/LoadingSpinner';
import { darkTheme } from '../theme';
import type { PrimerResponse } from '../types';

// PrimerPage — the /primer "Prep for class" tool (Paperloop Phase 5). The user
// types a topic string and receives an ephemeral, structured pre-class primer
// (overview + key concepts + priming questions) generated by DeepSeek from the
// topic ALONE — no note is read, no DB row is touched, nothing is persisted.
// A refresh clears the form and any generated primer (ephemeral by design).
// Renders inside the AppShell layout route via <Outlet />.

const pageWrap: React.CSSProperties = {
  minHeight: '100%',
  color: darkTheme.colors.textPrimary,
};
const inner: React.CSSProperties = { maxWidth: '760px', margin: '0 auto' };
const card: React.CSSProperties = {
  background: darkTheme.colors.bgSecondary,
  border: `1px solid ${darkTheme.colors.borderColor}`,
  borderRadius: darkTheme.borderRadius.lg,
  padding: '24px',
};
const label: React.CSSProperties = {
  display: 'block',
  fontSize: '13px',
  fontWeight: 600,
  marginBottom: '6px',
  color: darkTheme.colors.textSecondary,
};
const field: React.CSSProperties = {
  width: '100%',
  padding: '12px 14px',
  background: darkTheme.colors.bgTertiary,
  border: `1px solid ${darkTheme.colors.borderColor}`,
  borderRadius: darkTheme.borderRadius.md,
  color: darkTheme.colors.textPrimary,
  fontSize: '14px',
  outline: 'none',
  boxSizing: 'border-box',
  marginBottom: '18px',
};
const primaryBtn: React.CSSProperties = {
  padding: '12px 20px',
  background: darkTheme.colors.accent,
  border: 'none',
  color: '#fff',
  borderRadius: darkTheme.borderRadius.md,
  cursor: 'pointer',
  fontWeight: 600,
  fontSize: '15px',
  transition: darkTheme.transitions.default,
};
const sectionCard: React.CSSProperties = { ...card, marginTop: '20px' };
const sectionHeading: React.CSSProperties = {
  fontSize: '16px',
  fontWeight: 700,
  margin: '0 0 12px 0',
  color: darkTheme.colors.textPrimary,
};
const listStyle: React.CSSProperties = {
  margin: 0,
  paddingLeft: '20px',
  display: 'flex',
  flexDirection: 'column',
  gap: '8px',
  color: darkTheme.colors.textSecondary,
  fontSize: '14px',
  lineHeight: 1.6,
};

export default function PrimerPage() {
  const [topic, setTopic] = useState('');
  const [primer, setPrimer] = useState<PrimerResponse | null>(null);
  const [isLoading, setIsLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const trimmed = topic.trim();
    if (!trimmed) {
      toast.error('Please enter a topic.');
      return;
    }
    try {
      setIsLoading(true);
      const result = await api.ai.generatePrimer(trimmed);
      setPrimer(result);
    } catch (err) {
      logger.error('primer', 'Failed to generate primer', err);
      toast.error('Could not generate a primer. Please try again.');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div style={pageWrap}>
      <div style={inner}>
        <h1 style={{ fontSize: 'clamp(22px, 4vw, 30px)', fontWeight: 'bold', margin: '0 0 6px 0' }}>
          Prep for class
        </h1>
        <p
          style={{
            margin: '0 0 24px 0',
            color: darkTheme.colors.textSecondary,
            fontSize: '15px',
          }}
        >
          Type a topic and get a quick primer — an overview, the key concepts, and questions to
          think about before class.
        </p>

        <form style={card} onSubmit={handleSubmit}>
          <label style={label} htmlFor="primer-topic">
            Topic
          </label>
          <input
            id="primer-topic"
            style={field}
            value={topic}
            onChange={(event) => setTopic(event.target.value)}
            placeholder="e.g. Photosynthesis, the French Revolution, Newton's laws of motion"
            disabled={isLoading}
          />
          <button type="submit" style={primaryBtn} disabled={isLoading}>
            {isLoading ? 'Generating…' : 'Generate primer'}
          </button>
        </form>

        {isLoading && (
          <div style={{ marginTop: '24px' }}>
            <LoadingSpinner message="Building your primer..." />
          </div>
        )}

        {primer && !isLoading && (
          <div>
            <section style={sectionCard} aria-labelledby="primer-overview-heading">
              <h2 id="primer-overview-heading" style={sectionHeading}>
                Overview
              </h2>
              <p
                style={{
                  margin: 0,
                  color: darkTheme.colors.textSecondary,
                  fontSize: '14px',
                  lineHeight: 1.7,
                }}
              >
                {primer.overview || 'No overview was generated. Try a more specific topic.'}
              </p>
            </section>

            <section style={sectionCard} aria-labelledby="primer-concepts-heading">
              <h2 id="primer-concepts-heading" style={sectionHeading}>
                Key concepts
              </h2>
              {primer.key_concepts.length > 0 ? (
                <ul style={listStyle}>
                  {primer.key_concepts.map((concept, index) => (
                    <li key={`concept-${index}`}>{concept}</li>
                  ))}
                </ul>
              ) : (
                <p style={{ margin: 0, color: darkTheme.colors.textSecondary, fontSize: '14px' }}>
                  No key concepts were generated.
                </p>
              )}
            </section>

            <section style={sectionCard} aria-labelledby="primer-questions-heading">
              <h2 id="primer-questions-heading" style={sectionHeading}>
                Questions to think about
              </h2>
              {primer.questions.length > 0 ? (
                <ul style={listStyle}>
                  {primer.questions.map((question, index) => (
                    <li key={`question-${index}`}>{question}</li>
                  ))}
                </ul>
              ) : (
                <p style={{ margin: 0, color: darkTheme.colors.textSecondary, fontSize: '14px' }}>
                  No questions were generated.
                </p>
              )}
            </section>
          </div>
        )}
      </div>
    </div>
  );
}
